name: project_3

channels:
    - conda-forge

dependencies:
  - python=3.8
  - autopep8
  - pylint
  - dvc
  - numpy
  - pandas
  - scikit-learn
  - pytest
  - requests
  - fastapi
  - httpx
  - uvicorn
  - gunicorn
  - git