name: project_4

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - dill
  - autopep8
  - pylint
  - dvc
  - numpy
  - pandas
  - scikit-learn
  - pytest
  - requests
  - fastapi
  - httpx
  - uvicorn
  - gunicorn
  - git